<%@ Page Title="" Language="C#" MasterPageFile="~/EmployeePage/Employee.master" AutoEventWireup="true" CodeBehind="EmpItem.aspx.cs" Inherits="PetAdopt.EmployeePage.EmpItem" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder3" runat="server">
    <table>
        <tr>
            <td>
                <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" OnRowDeleting="GridView1_RowDeleting">
                    <Columns>
                        <asp:BoundField DataField="itemCode" HeaderText="商品号" />
                        <asp:BoundField DataField="itemType" HeaderText="商品类型" />
                        <asp:BoundField DataField="itemName" HeaderText="商品名" />
                        <asp:BoundField DataField="price" HeaderText="价格" DataFormatString="{0:C}"/>
                        <asp:BoundField DataField="sales" HeaderText="销量" />
                        <asp:TemplateField>
                            <ItemTemplate>
                                <asp:Button  runat="server" Text="查看评价" CommandName="ReviewCommand" OnClick="CheckReview" CommandArgument=<%# Eval("itemCode") %>/>
                            </ItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                </asp:GridView>
            </td>
            <td>
                <asp:Panel runat="server" ID="Panel1" Height="500px" ScrollBars="Vertical" Visible="False" Width="200px">
                <asp:ListView ID="ListView1" runat="server">
                    <LayoutTemplate>
                        <div style="display: flex; flex-wrap: wrap;">
                            <asp:PlaceHolder ID="itemPlaceholder" runat="server" />
                        </div>
                    </LayoutTemplate>
                    <ItemTemplate>
                        <div style="margin: 10px;">
                        <asp:Label runat="server" Text=<%# Eval("userName") %>>
                        </asp:Label>
                        <br />
                        <asp:Label runat="server" Text=<%# "评分"+Eval("rate") %>>
                        </asp:Label>
                        <br />
                        <asp:Label runat="server" Text=<%# Eval("content")%>>
                        </asp:Label>
                        <br />
                        <asp:Label runat="server" Text=<%# Eval("pushTime")%>>
                        </asp:Label>
                        <br />
                            </div>
                    </ItemTemplate>
                </asp:ListView>
                </asp:Panel>
                <br />
            </td>
        </tr>
        <tr>
            <td>

                <table style="width: 100%">
                    <tr>
                        <td style="width: 131px">商品类型：</td>
                        <td style="width: 208px">
                            <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
                        </td>
                        <td>
                            <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="TextBox1" ErrorMessage="请输入商品类型" ValidationGroup="1"></asp:RequiredFieldValidator>
                        </td>
                    </tr>
                    <tr>
                        <td style="width: 131px">商品名：</td>
                        <td style="width: 208px">
                            <asp:TextBox ID="TextBox2" runat="server"></asp:TextBox>
                        </td>
                        <td>
                            <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ControlToValidate="TextBox2" ErrorMessage="请输入商品名" ValidationGroup="1"></asp:RequiredFieldValidator>
                        </td>
                    </tr>
                    <tr>
                        <td style="width: 131px">价格：</td>
                        <td style="width: 208px">
                            <asp:TextBox ID="TextBox3" runat="server"></asp:TextBox>
                        </td>
                        <td>
                            <asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server" ControlToValidate="TextBox3" ErrorMessage="请输入价格" ValidationGroup="1"></asp:RequiredFieldValidator>
                        </td>
                    </tr>
                    <tr>
                        <td style="width: 131px; height: 36px"></td>
                        <td style="width: 208px; height: 36px">
                            <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="上传" ValidationGroup="1" />
                        </td>
                        <td style="height: 36px"></td>
                    </tr>
                </table>
            </td>
            <td>

            </td>
        </tr>
    </table>
</asp:Content>
