<%@ Page Title="" Language="C#" MasterPageFile="~/UserPage/User.master" AutoEventWireup="true" CodeBehind="UserCart.aspx.cs" Inherits="PetAdopt.UserCart" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder3" runat="server">
    <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" OnRowDeleting="GridView1_RowDeleting" AutoGenerateColumns="False">
        <Columns>
            <asp:BoundField DataField="Code" HeaderText="商品号" />
            <asp:BoundField DataField="Name" HeaderText="商品名" />
            <asp:BoundField DataField="Amount" HeaderText="已选数量" />
            <asp:BoundField DataField="Price" HeaderText="单价" DataFormatString="{0:C}"/>
            <asp:BoundField DataField="Total" HeaderText="单项总价" DataFormatString="{0:C}" />
        </Columns>
    </asp:GridView>
    <asp:Label ID="Label1" runat="server" Text="总价：¥"></asp:Label>
    <asp:Label ID="Label2" runat="server"></asp:Label>
    <br />
    <asp:Label ID="Label3" runat="server" Text="购买前请输入收货地址："></asp:Label>
    <asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
    <br />
    <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="购买" />
    <asp:Button ID="Button2" runat="server" OnClick="Button2_Click" Text="清空" />
</asp:Content>
